### ISSUE TITLE
java.lang.ClassCastException (possible crash)

### ISSUE THREAD

**Issue by NattoRiisa** [NemoNotFound/NemosFarming#1]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-08-23 14:40:55
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1542 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_1542 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1d057a39)
	at net.minecraft.class_2344.modifyExpressionValue$ggi000$nemos-farming$onLandedUpon(class_2344.java:2024)
	at net.minecraft.class_2344.method_9554(class_2344.java:104)
	at net.minecraft.class_1297.method_5623(class_1297.java:1363)
	at net.minecraft.class_1297.method_5784(class_1297.java:753)
	at net.minecraft.class_1542.method_5773(class_1542.java:165)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2344.modifyExpressionValue$ggi000$nemos-farming$onLandedUpon(class_2344.java:2024)
	at net.minecraft.class_2344.method_9554(class_2344.java:104)
	at net.minecraft.class_1297.method_5623(class_1297.java:1363)
	at net.minecraft.class_1297.method_5784(class_1297.java:753)
	at net.minecraft.class_1542.method_5773(class_1542.java:165)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 490
	Entity Name: Wheat Seeds
	Entity's Exact location: 334.44, 78.94, 642.11
	Entity's Block location: World: (334,78,642), Section: (at 14,14,2 in 20,4,40; chunk contains blocks 320,-64,640 to 335,319,655), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Entity's Momentum: -0.00, -0.27, -0.01
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['NattoRiisa'/24, l='ServerLevel[New World]', x=335.32, y=78.94, z=645.18]]
	Chunk stats: 1964
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,77,688), Section: (at 0,13,0 in 15,4,43; chunk contains blocks 240,-64,688 to 255,319,703), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Level time: 2190 game time, 2190 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: true. Commands: false
	Level weather: Rain time: 44154 (now: false), thunder time: 58294 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 298
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.1, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 2297748200 bytes (2191 MiB) / 5905580032 bytes (5632 MiB) up to 5905580032 bytes (5632 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600G with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21914.4000
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 27276.92
	Virtual memory used (MiB): 23235.24
	Swap memory total (MiB): 11535.74
	Swap memory used (MiB): 1321.27
	Space in storage for jna.tmpdir (MiB): available: 5096.39, total: 476937.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 5096.39, total: 476937.00
	Space in storage for io.netty.native.workdir (MiB): available: 5096.39, total: 476937.00
	Space in storage for java.io.tmpdir (MiB): available: 10671.30, total: 244081.31
	Space in storage for workdir (MiB): available: 5096.39, total: 476937.00
	JVM Flags: 10 total; -Xmx5632M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		accessories: Accessories 1.0.0-beta.30+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		achiopt: AchievementOptimizer 1.21-1.1.0
		additionalstructures: Additional Structures 5.0.0-fabric
		adorabuild_structures: AdoraBuild: Structures 2.7.0
		advancednetherite: Advanced Netherite 2.1.6-1.21
		alloy_forgery: Alloy Forgery 2.4.1+1.21
		animatica: Animatica 0.6.1+1.21
		appleskin: AppleSkin 3.0.5+mc1.21
		architectury: Architectury 13.0.6
		athena: Athena 4.0.1
		authme: Auth Me 8.0.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
		autofish: AutoFish 1.0.3
		autotools: AutoTools 2.1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		badoptimizations: BadOptimizations 2.1.4
		balm-fabric: Balm 21.0.18
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		beeg-smol: Beeg Smol 1.1.0
		better_climbing: Better Climbing 3
		better_impaling: Better Impaling 3.0
		betterallay: Better Allay [FABRIC]-1.4.0-1.21
		betterclouds: Better Clouds 1.7.1+1.21
		betterf3: BetterF3 11.0.1
		blackbarconcealer: Black Bar Concealer 1.0.0
		blahaj: Blåhaj 2.0.0
		blastingraw: BlastingRaw 1.21.1-2-fabric
		blastingsand: Smelting Sand In a Blast Furnace 1.21.1-11-fabric
		blocky-bubbles: Blocky Bubbles 1.2.0+1.21
		boatbreakfix: Boat Break Fix 1.0.2
		boathud_extended: BoatHUD (Extended) 1.1.0
		boostedexperience: BoostedExperience 1.2
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.10.1-1.21
			multipart_entities: MultipartEntities 1.7-1.21
		brb: Better Recipe Book 1.10.0-rc5+1.21
		brickfurnace: Brick Furnace 1.21-4.1.0.1
		brickhopper: Brick Hopper 1.21-3.1.0.0
		buffedsculkcatalysts: Buffed Sculk Catalysts 1.0.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.109+1.21
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.109+1.21
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.109+1.21
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.109+1.21
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.109+1.21
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.109+1.21
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.109+1.21
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.109+1.21
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.109+1.21
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.109+1.21
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.109+1.21
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.109+1.21
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.109+1.21
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.109+1.21
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.109+1.21
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.109+1.21
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.109+1.21
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		capes: Capes 1.5.4+1.21
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		chargedcharms: Charged Charms 2.0.1.1
			spectrelib: SpectreLib 0.17.2+1.21
		chatpatches: Chat Patches 210.6.5.1
		cicada: CICADA 0.8.3+1.21-and-above
		clientsidenoteblocks: ClientSideNoteblocks 2.8
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 18.0.0.2
		cog: CobbleOre Generator 2.1.1+1.21
		collective: Collective 7.84
		collisionfix: CollisionFix 1.0.1
		compact_storage: CompactStorage 8.0.75
		completedshieldfix: Walksy's Complete Shield Fixes 1.3.0
		continuity: Continuity 3.0.0-beta.5+1.21
		copperhopper: Copper Hopper 0.9.3+1.21
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.7
		craftingtweaks: Crafting Tweaks 21.1.2
		craftsman_bows: Craftsman's bows 1.0.1
		cropsloverain: Crops Love Rain 2.1.1
		cullleaves: Cull Leaves 3.4.0
		customlevelcolour: Custom Level Colour 1.0.0+1.21
		dark-sky: Dark Sky 1.1.2
		darkenchanting: Dark Enchanting 1.3.0+1.21
			omegaconfig: Omega Config Architectury 1.5.1
		debugify: Debugify 1.21+1.0
		deuf_refabricated: DEUF Refabricated 1.1.0
		diamondrails: Diamond Rails 1.0.0
		diversity: Diversity 1.3.4+1.21
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
			polymer-core: Polymer (Core) 0.9.10+1.21.1
				polymer-networking: Polymer (Networking) 0.9.10+1.21.1
					polymer-common: Polymer (Common) 0.9.10+1.21.1
						packet_tweaker: Packet Tweaker 0.5.5+1.21
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.10+1.21.1
		dragonloot: DragonLoot 1.1.6
		dynamiccrosshair: Dynamic Crosshair 8.1+1.21
			dynamiccrosshair-api: DynamicCrosshair API 1.1
			libbamboo: libbamboo 1.21.0.2
		dynamicsoundfilters: Dynamic Sound Filters 1.4.0+1.21
		easyvillagertrade: EasyVillagerTrade 1.2.1-1.21
		eg_fix_horizontal_camera_lag: Fix Horizontal Camera Lag 1.1
		energizedpower: Energized Power 1.21-2.12.1-fabric
			team_reborn_energy: Energy 4.1.0
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.21
		enhanced_quarries: Enhanced Quarries 1.4.8
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entity_model_features: Entity Model Features 2.2
		entity_texture_features: Entity Texture Features 6.2
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.7
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.8
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.10
		expanded_bow_enchanting: Expanded Bow Enchanting 1.1.1
		expanded_crossbow_enchanting: Expanded Crossbow Enchanting 1.0.1
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.10
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.1.0
		expandedstorage: Expanded Storage 14.1.1
		explorify: Explorify 1.6.1
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.0+kotlin.2.0.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.2
		fallingtree: FallingTree 1.21.0.8
		faster-random: Faster Random 5.1.0
		fasttrading: Fast Trading 0.1.5+1.21
		ferritecore: FerriteCore 7.0.0
		feytweaks: FeyTweaks 1.21-1.2.8
		firehud: Fire Hud 1.2-1.21
		fishingrodfix: Fishing rod fix 1.21-0.3
		fishnostuck: Fish No Stuck 1.0.3
		fixed-levels: Fixed Levels 1.3.0+1.21
			blue_endless_jankson: jankson 1.2.3
		forgeconfigapiport: Forge Config API Port 21.0.8
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		frost: New FrostWalker 1.2.3
		fuelinfo: FuelInfo 2.1+1.21
		fzzy_config: Fzzy Config 0.3.5+1.21
			net_peanuuutz_tomlkt_tomlkt-jvm: tomlkt-jvm 0.3.7
		galvanizedveneers: GalvanizedVeneers 1.2.1
		gameclock: GameClock 1.2.0
		gd_betterloot: GD BetterLoot 1.0b3
		geckolib: GeckoLib 4 4.5.8
		guarding: Guarding 1.21.1-2.7.3
		held-item-info: Held Item Info 1.7.0
		higher_nether: Higher Nether 1.0.2
		hopobettermineshaft: Hopo Better Mineshaft 1.2.7
		hopobetterruinedportal: Hopo Better Ruined Portal 1.4.3
		hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.2.0
		horsebuff: HorseBuff 2.1.8
		idwtialsimmoedm: idwtialsimmoedm 0.3.1+1.21
		ikwid: I Know What I'm Doing 1.0-SNAPSHOT
		immediatelyfast: ImmediatelyFast 1.2.20+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.35+mc1.21
		infinitetrading: Infinite Trading 4.5
		inventoryprofilesnext: Inventory Profiles Next 2.0.4
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		ironbookshelves: Iron Bookshelves 1.21.1-1.3.5-fabric
			configlibtxf: ConfigLib TXF 7.2.1-fabric
		ironladders: Iron Ladders 2.5.2
		iseelava: I See Lava 1.0.1
		jade: Jade 15.1.5+fabric
		java: OpenJDK 64-Bit Server VM 21
		jukebox_action_bar_fix: Jukebox Action Bar Fix 3
		jukeboxcustomdiscfix: Jukebox Custom Disc Fix 0.1.5-1.21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		lake_crash_fix: Lake Crash Fix 1.0
		languagereload: Language Reload 1.6.1+1.21
		lavender: Lavender 0.1.12+1.21
			lavender-md: lavender-md 0.1.1+1.21
			lavender-md-owo-ui: lavender-md-owo-ui 0.1.1+1.21
		leahs-immersive-thunder: Immersive Thunder 1.21+1.2.2
		libertyvillagers: Liberty's Villagers 1.0.15+fabric+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
		libipn: libIPN 6.0.2
		lithium: Lithium 0.13.0
		long_books: Long Books 1.0
		magicmirror: MagicMirror 1.1.3
		mambience: MAmbience 5.5.1+1.21
		mc229142fix: MC229142Fix 1.0
		mcpitanlib: MCPitanLib 2.3.3-fix.1-1.21-fabric
			compatdatapacks76: CompatDatapacks 1.0.7.210-fabric
			org_yaml_snakeyaml: snakeyaml 2.0
		medieval_buildings: Medieval Buildings 1.0.2
		medievalend: Medieval Buildings [The End Edition] 1.0.2
		mes: Moog's End Structures 1.3.2-1.21-fabric
		midnightlib: MidnightLib 1.5.8
		minecraft: Minecraft 1.21
		mns: Moog's Nether Structures 1.0.2-1.21-fabric
		modelfix: Model Gap Fix 1.21-1.6
		moderner_beta: Moderner Beta 1.4.0+1.21
		modernfix: ModernFix 5.19.1+mc1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		monkeylib538: MonkeyLib538 2.0.1
			monkeylib538-common: MonkeyLib538 2.0.1
		monolib: MonoLib 1.3.0
		more_beautiful_torches: More Beautiful Torches 3.0.0
		more_fossils: More Fossils 2.0.1
		moreculling: More Culling 0.26.0
			com_github_fallen-breath_conditional-mixin: conditional-mixin v0.6.2
			mixinsquared: MixinSquared 0.1.1
		morediscs: More Music Discs 1.21.1-34-fabric
		moremcmeta: MoreMcmeta 1.21-4.4.7
			moremcmeta_animation_plugin: MoreMcmeta Animation Plugin 1.21-1.0.3
			moremcmeta_gui_plugin: MoreMcmeta GUI Plugin 1.21-1.0.1
			moremcmeta_json_parser_plugin: MoreMcmeta JSON Parser Plugin 1.21-1.1.1
			moremcmeta_properties_parser_plugin: MoreMcmeta Properties Parser Plugin 1.21-1.1.5
			moremcmeta_texture_plugin: MoreMcmeta Texture Plugin 1.21-1.0.1
		moremcmeta_emissive_plugin: MoreMcmeta Emissive Textures Plugin 1.21-2.0.5
		morenemoswoodcuttervariants: More Nemo's Woodcutter Variants 1.1.0-1.21
		mostructures: Mo' Structures 1.5.0+1.21
		movingelevators: Moving Elevators 1.4.7+a
		mr_battle_towers: Battle Towers 1.1.1
		mr_beyondenchant: BeyondEnchant 1.2.0
		mr_blasting_plus: Blasting Plus 1.3
		mr_copper_doorcutting: Copper Door Cutting 48.1
		mr_copper_uses: Copper Uses 1.0
		mr_craft_spawneggs: Craft Spawn Eggs 1-v.2.1.3
		mr_craft_tridents: Craftable Trident 48.2
		mr_dungeons: Dungeons+ 1.8.4b
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.3
		mr_enchantments_encore: Enchantments Encore 1.7b
		mr_fortunate_ancientdebris: Fortunate Ancient Debris 1.2
		mr_ghast_tweaks: Ghast Tweaks 2
		mr_increased_railsrecipeoutput: Increased Rails Recipe Output 1.2
		mr_infinite_ominousbottles: infinite ominous bottles 1.0
		mr_just_anotherstructurepack: Just Another Structure Pack 2.0
		mr_katters_structures: Katters Structures 2.0
		mr_larger_oreveinsdeluxe: Larger Ore Veins: Deluxe 1.2.2
		mr_mine_treasure: Mine Treasure 1.4.3
		mr_miners_delight: Miner's Delight! 3
		mr_minions: Minions 1-v2.0.0
		mr_mob_heads: Mob Heads 1-v.2.6.5
		mr_neoenchant: Neo Enchant+ 5.6.0
		mr_panda_temple: Panda Temple 1-V1
		mr_perlinescent_caves: Perlinescent Caves 1-v1.0
		mr_qraftyfied: qraftyfied 8.0.1
		mr_qraftys_japanesevillages: qrafty's Japanese Villages 2.2
		mr_rmes_campfireleather: RME's Campfire Leather 1.1.5
		mr_strayed_fatesforsaken: STRAYED FATES: Forsaken 1-v2.0.0.0
		mr_true_ending: True Ending: Ender Dragon Overhaul 1-v1.1.1
		mr_two_shulkershellsdrop: Shulkers Drop Two Shells 1-v.2.1.0
		mr_upgrade_templatevaults: Upgrade Template Vaults 1-v1.0.0
		mr_village_heroplus: Village Hero+ 4
		mr_yggdrasil_structure: Yggdrasil 1.4.0
		mvs: Moog's Voyager Structures 4.1.3-1.21-fabric
		mythicmetals: Mythic Metals 0.20.0+1.21
			additionalentityattributes: Additional Entity Attributes 1.8.0+1.21
			common-protection-api: Common Protection API 1.0.0
		mythicupgrades: Mythic Upgrades 4.1.4+mc1.21
		necronomicon: Necronomicon 1.5.0
		nemos-better-mending: Nemo's Better Mending 1.1.1-1.21
		nemos-creatures: Nemo's Creatures SNAPSHOT-24w33a-1.21
		nemos-farming: Nemo's Farming 1.1-1.21
			mixinextras: MixinExtras 0.5.0-beta.2
		nemos-woodcutter: Nemo's Woodcutter 1.11.3-1.21
		netherstardupe: Nether Star Duplication 1.0
		nmc: No Mining Cooldown 2.3
		no_double_sneak: No Double Sneak 1.1
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		nullscape: Nullscape 1.2.7
		obsidianequipment: Obsidian Equipment 1.0.2
		obsidianui: ObsidianUI 0.2.7+mc1.21
		omnihopper: Omni-Hopper 2.3.2+1.21
			cooldown-coordinator: Cooldown Coordinator 0.7.2
		onlyhammersandexcavators: OnlyHammersAndExcavators 1.21-0.3
		optigui: OptiGUI 2.3.0-beta.2+1.21
			org_apache_commons_commons-text: commons-text 1.12.0
			org_ini4j_ini4j: ini4j 0.5.4
		oritech: Oritech 0.8.1
		owo: oωo 0.12.11+1.21
			io_wispforest_endec_jankson: jankson 0.1.3
		packet-exception-logger: packet-exception-logger 1.1.0
		packetfixer: Packet Fixer 1.4.1
		particle_core: Particle Core 0.2.4+1.21
			conditional-mixin: conditional mixin 0.5.1
		particlerain: Particle Rain 2.1.4
		philipsbiomefeatures: Philip's Biome Features 1.5
		philipsruins: Philip`s Ruins 1.21
		potionring: Potion Ring - REFORGED 1.21-1.0
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		puzzle: Puzzle 1.6.3+1.21
			puzzle-base: Puzzle Base 1.6.3+1.21
			puzzle-gui: Puzzle GUI 1.6.3+1.21
			puzzle-models: Puzzle Models 1.6.3+1.21
			puzzle-splashscreen: Puzzle Splash Screen 1.6.3+1.21
		railoptimization: RailOptimization 1.2
		reborncore: Reborn Core 5.11.10
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		rendertweaks: Render Tweaks 1.1.0
		repurposed_structures: Repurposed Structures 7.5.4+1.21-fabric
		reputation: Your Reputation 0.2.7+jade.1.21
		resourcefullib: Resourceful Lib 3.0.9
			com_teamresourceful_bytecodecs: bytecodecs 1.1.2
			com_teamresourceful_yabn: yabn 1.0.3
		respawningshulkers: Respawning Shulkers 4.0
		roguelike: Roguelike Dungeons 2.0.8-1.21-fabric
		rose_bush: Rose Bush 1.1.2
		roughlyenoughitems: Roughly Enough Items 16.0.754
			error_notifier: Error Notifier 1.0.9
		ryoamiclights: RyoamicLights 0.2.11+mc1.21.1
		scalablelux: ScalableLux 0.1.0+rc.1+fabric.43c9882
		scribble: Scribble 1.2.2
		sculk_expansion_mr: Sculk Expansion 1.3.3
		showmeyourskin: Show Me Your Skin! 1.11.3+1.21
		shutter: Shutter 1.1
		simple_copper_pipes: Simple Copper Pipes 2.0
		simpleblockoverlay: Simple Block Overlay 1.4.3
		simplehudenhanced: Simple Hud Enhanced 4.7.2
		sketch: Sketch 1.21.1-1.2.1
		skinlayers3d: 3d-Skin-Layers 1.6.7
		smeltingstone: Smelting Cobblestone In a Blast Furnace 1.21.1-0-fabric
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		stackcalc: StackCalc Revived 1.1.1
		status-effect-bars: Status Effect Bars 1.0.6
		stutterfix: StutterFix mc1.21-0.2.3
		superbettergrass: SuperBetterGrass 1.5.3+1.21
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+b
		taxfreelevels: Tax Free Levels 1.3.12
		tclayer: Accessories Trinkets Compat Layer 3.10.0+beta.7
		techreborn: Tech Reborn 5.11.10
		tectonic: Tectonic 2.4.1a
		the_bumblezone: The Bumblezone - Fabric 7.6.22+1.21-fabric
		timestacker: TimeStacker 1.1.4
		toms_storage: Tom's Simple Storage Mod 2.0.10
		tooltipscroll: Tooltip Scroll 1.4.0+1.21
			lilylib: LilyLib 1.2.1+1.21
		toros-auto-attack: Toro's Auto Attack 1.2
		travelersbackpack: Traveler's Backpack fabric-1.21-10.0.6
		trialrestock: Trial Vault Restock 1.0.3
		ukulib: ukulib 1.4.0+1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		unloadedactivity: Unloaded Activity 0.6.3
		unwrecked_ships: Unwrecked Ships 2.0.0
		vanilla_claws: Vanilla Claws 1.2
		vanillafix: VanillaIcecreamFix 1.2.2-beta
		videotape: Video Tape 1.0.0
		wabi_sabi_structures: Wabi-Sabi Structures 3.0.0
		water-in-the-nether: Water In The Nether 2.0.0+1.21
		waystones: Waystones 21.0.8
		wheelbarrow: Wheelbarrow 1.0.2
		wilderwild: Wilder Wild 2.4.13-mc1.21.1
			frozenlib: FrozenLib 1.8.5-mc1.21.1
		woodenhopper: Wooden Hopper 1.21-3.1.0.0
		wover: WorldWeaver 21.0.13
			wover-biome: WorldWeaver - Biome API 21.0.13
			wover-block: WorldWeaver - Block and Item API 21.0.13
			wover-common: WorldWeaver - Common API 21.0.13
			wover-core: WorldWeaver - Core API 21.0.13
			wover-datagen: WorldWeaver - Datagen API 21.0.13
			wover-events: WorldWeaver - Events API 21.0.13
			wover-feature: WorldWeaver - Feature API 21.0.13
			wover-generator: WorldWeaver - World Generator API 21.0.13
			wover-item: WorldWeaver - Item API 21.0.13
			wover-math: WorldWeaver - Math API 21.0.13
			wover-preset: WorldWeaver - World Preset API 21.0.13
			wover-recipe: WorldWeaver - Recipe API 21.0.13
			wover-structure: WorldWeaver - Structure API 21.0.13
			wover-surface: WorldWeaver - Surface API 21.0.13
			wover-tag: WorldWeaver - Tag API 21.0.13
			wover-ui: WorldWeaver - UI API 21.0.13
			wunderlib: WunderLib 21.0.8
		xaerominimap: Xaero's Minimap 24.3.0
		xaeroworldmap: Xaero's World Map 1.38.8
		xp_storage: XP Storage 1.5.10+1.21
		xp_storage_trinkets: XP Storage - Trinkets 1.0.1+1.21
		xtraarrows: Xtra Arrows 3 3.4.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zero-tick-crops: 0 Tick Crops 1.0.0+1.20.5+
		zoomify: Zoomify 2.14.0+1.21
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['NattoRiisa'/24, l='ServerLevel[New World]', x=335.32, y=78.94, z=645.18]]
	Active Data Packs: vanilla, fabric, accessories, additionalentityattributes, additionalstructures, adorabuild_structures, advancednetherite, alloy_forgery, autotools, balm-fabric (incompatible), better_impaling, blahaj, blastingraw, blastingsand, bosses_of_mass_destruction, brickfurnace, brickhopper (incompatible), chargedcharms (incompatible), collective, compact_storage, copperhopper, craftable_enchanted_golden_apple, craftingtweaks (incompatible), craftsman_bows, darkenchanting, diamondrails, diversity (incompatible), dragonloot, dynamiccrosshair-api, energizedpower (incompatible), enhanced_quarries, expandedstorage, explorify, fabric-convention-tags-v2, firehud, frost, frozenlib, galvanizedveneers, gd_betterloot, guarding, higher_nether (incompatible), hopobettermineshaft, hopobetterruinedportal, hopobetterunderwaterruins, ironbookshelves, ironladders, libertyvillagers, magicmirror, mambience, medieval_buildings (incompatible), medievalend (incompatible), mes (incompatible), mns (incompatible), moderner_beta, more_beautiful_torches (incompatible), more_fossils (incompatible), moreculling, morediscs, morenemoswoodcuttervariants, mostructures, movingelevators (incompatible), mr_battle_towers, mr_beyondenchant, mr_blasting_plus, mr_copper_doorcutting, mr_copper_uses (incompatible), mr_craft_spawneggs, mr_craft_tridents, mr_dungeons (incompatible), mr_dungeons_andtaverns, mr_enchantments_encore, mr_fortunate_ancientdebris, mr_ghast_tweaks, mr_increased_railsrecipeoutput, mr_infinite_ominousbottles (incompatible), mr_just_anotherstructurepack, mr_katters_structures, mr_larger_oreveinsdeluxe, mr_mine_treasure, mr_miners_delight, mr_minions, mr_mob_heads, mr_neoenchant, mr_panda_temple (incompatible), mr_perlinescent_caves, mr_qraftyfied, mr_qraftys_japanesevillages, mr_rmes_campfireleather, mr_strayed_fatesforsaken, mr_true_ending, mr_two_shulkershellsdrop, mr_upgrade_templatevaults (incompatible), mr_village_heroplus, mr_yggdrasil_structure, mvs (incompatible), mythicmetals, mythicupgrades, nemos-creatures, nemos-farming, nemos-woodcutter, netherstardupe, nullscape, obsidianequipment, omnihopper, onlyhammersandexcavators, oritech, philipsbiomefeatures, philipsruins, potionring, repurposed_structures, roguelike, sculk_expansion_mr, server_translations_api, shutter, simple_copper_pipes, sketch, smeltingstone, supermartijn642corelib (incompatible), techreborn, the_bumblezone, toms_storage, travelersbackpack, unwrecked_ships, vanilla_claws, vanillafix, wabi_sabi_structures, waystones (incompatible), wheelbarrow, wilderwild, woodenhopper (incompatible), wover-generator, wover-preset, wover-surface, wover-tag, xp_storage, xp_storage_trinkets, xtraarrows, tectonic:tectonic, frost:true_ice_still__false_server_only
	Available Data Packs: accessories, additionalentityattributes, additionalstructures, adorabuild_structures, advancednetherite, alloy_forgery, autotools, balm-fabric (incompatible), better_impaling, blahaj, blastingraw, blastingsand, bosses_of_mass_destruction, brickfurnace, brickhopper (incompatible), bundle, chargedcharms (incompatible), collective, compact_storage, copperhopper, craftable_enchanted_golden_apple, craftingtweaks (incompatible), craftsman_bows, darkenchanting, diamondrails, diversity (incompatible), dragonloot, dynamiccrosshair-api, energizedpower (incompatible), enhanced_quarries, expandedstorage, explorify, fabric, fabric-convention-tags-v2, firehud, frost, frost:true_ice_still__false_server_only, frozenlib, galvanizedveneers, gd_betterloot, guarding, higher_nether (incompatible), hopobettermineshaft, hopobetterruinedportal, hopobetterunderwaterruins, ironbookshelves, ironladders, libertyvillagers, magicmirror, mambience, medieval_buildings (incompatible), medievalend (incompatible), mes (incompatible), mns (incompatible), moderner_beta, moderner_beta:reduced_height, more_beautiful_torches (incompatible), more_fossils (incompatible), moreculling, morediscs, morenemoswoodcuttervariants, mostructures, movingelevators (incompatible), mr_battle_towers, mr_beyondenchant, mr_blasting_plus, mr_copper_doorcutting, mr_copper_uses (incompatible), mr_craft_spawneggs, mr_craft_tridents, mr_dungeons (incompatible), mr_dungeons_andtaverns, mr_enchantments_encore, mr_fortunate_ancientdebris, mr_ghast_tweaks, mr_increased_railsrecipeoutput, mr_infinite_ominousbottles (incompatible), mr_just_anotherstructurepack, mr_katters_structures, mr_larger_oreveinsdeluxe, mr_mine_treasure, mr_miners_delight, mr_minions, mr_mob_heads, mr_neoenchant, mr_panda_temple (incompatible), mr_perlinescent_caves, mr_qraftyfied, mr_qraftys_japanesevillages, mr_rmes_campfireleather, mr_strayed_fatesforsaken, mr_true_ending, mr_two_shulkershellsdrop, mr_upgrade_templatevaults (incompatible), mr_village_heroplus, mr_yggdrasil_structure, mvs (incompatible), mythicmetals, mythicupgrades, nemos-creatures, nemos-farming, nemos-woodcutter, netherstardupe, nullscape, obsidianequipment, omnihopper, onlyhammersandexcavators, oritech, philipsbiomefeatures, philipsruins, potionring, repurposed_structures, roguelike, sculk_expansion_mr, server_translations_api, shutter, simple_copper_pipes, sketch, smeltingstone, supermartijn642corelib (incompatible), techreborn, tectonic:tectonic, the_bumblezone, toms_storage, trade_rebalance, travelersbackpack, unwrecked_ships, vanilla, vanilla_claws, vanillafix, wabi_sabi_structures, waystones (incompatible), wheelbarrow, wilderwild, woodenhopper (incompatible), wover-generator, wover-preset, wover-surface, wover-tag, xp_storage, xp_storage_trinkets, xtraarrows
	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
	World Generation: Stable
	World Seed: -6197382037237876490
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.21

**Comment by NemoNotFound** [comment]
Uhh, interesting haha.
During my testing I didn't get this issue. Can you tell me, which armor you had and which mod version you used?

**Comment by NemoNotFound** [comment]
Never mind, I see which version you use. Which armor did you have?

**Comment by NattoRiisa** [comment]
funny story is that,,, i had (no) armor

**Comment by NattoRiisa** [comment]
this was on a new seed, new save, on a village

**Comment by NemoNotFound** [comment]
Ahh, and also relevant, which fabric loader version are you using?
I see that I left the minimum fabric loader version to 0.15.11 but use 0.16+

**Comment by NattoRiisa** [comment]
if im not mistaken i am using 0.16.2 (i think you mean 0.15.11)

**Comment by NattoRiisa** [comment]
currently attempting to reproduce with a separate pack with a smaller pick of mods just to check compats

**Comment by NemoNotFound** [comment]
Yes, I meant that haha
Hmm, 0.16.2 should be correct

**Comment by NattoRiisa** [comment]
here's a crash report with FAR less mods
yep this is potentially an issue with the mod, more specifically (probably) the onLandedUpon code
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-08-23 15:06:14
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_1542 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_1542 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1d057a39)
	at net.minecraft.class_2344.modifyExpressionValue$boe000$nemos-farming$onLandedUpon(class_2344.java:524)
	at net.minecraft.class_2344.method_9554(class_2344.java:104)
	at net.minecraft.class_1297.method_5623(class_1297.java:1363)
	at net.minecraft.class_1297.method_5784(class_1297.java:753)
	at net.minecraft.class_1542.method_5773(class_1542.java:165)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2344.modifyExpressionValue$boe000$nemos-farming$onLandedUpon(class_2344.java:524)
	at net.minecraft.class_2344.method_9554(class_2344.java:104)
	at net.minecraft.class_1297.method_5623(class_1297.java:1363)
	at net.minecraft.class_1297.method_5784(class_1297.java:753)
	at net.minecraft.class_1542.method_5773(class_1542.java:165)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 2836
	Entity Name: Wheat
	Entity's Exact location: -3445.83, 70.94, -1332.46
	Entity's Block location: World: (-3446,70,-1333), Section: (at 10,6,11 in -216,4,-84; chunk contains blocks -3456,-64,-1344 to -3441,319,-1329), Region: (-7,-3; contains chunks -224,-96 to -193,-65, blocks -3584,-64,-1536 to -3073,319,-1025)
	Entity's Momentum: 0.06, -0.27, 0.06
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['NattoRiisa'/14, l='ServerLevel[New World]', x=-3441.30, y=81.68, z=-1297.09]]
	Chunk stats: 2604
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,66,-416), Section: (at 0,2,0 in -14,4,-26; chunk contains blocks -224,-64,-416 to -209,319,-401), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 2393 game time, 2393 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: false
	Level weather: Rain time: 177505 (now: false), thunder time: 32120 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 177
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.class_1132.method_3748(class_1132.java:114)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.1, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1406128872 bytes (1340 MiB) / 2181038080 bytes (2080 MiB) up to 5905580032 bytes (5632 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600G with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21914.4000
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 27276.92
	Virtual memory used (MiB): 21039.77
	Swap memory total (MiB): 11535.74
	Swap memory used (MiB): 1060.73
	Space in storage for jna.tmpdir (MiB): available: 4934.01, total: 476937.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 4934.01, total: 476937.00
	Space in storage for io.netty.native.workdir (MiB): available: 4934.01, total: 476937.00
	Space in storage for java.io.tmpdir (MiB): available: 10582.91, total: 244081.31
	Space in storage for workdir (MiB): available: 4934.01, total: 476937.00
	JVM Flags: 10 total; -Xmx5632M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		continuity: Continuity 3.0.0-beta.5+1.21
		fabric-api: Fabric API 0.102.1+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b55973446a
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc6a
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a76a
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c6a
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a76a
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c6a
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b36a
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b55973446a
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.20+7f945d5b6a
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.6.0+605f22ad6a
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a76a
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+1daea2156a
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.17+16c4ae256a
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b996a
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b996a
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae066a
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd96a
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc9216a
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+780172706a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b36a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a56a
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a56a
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c6a
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b6a
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a936a
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c6a
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+650897126a
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b6a
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c6a
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c6a
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b36a
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e6a
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea2156a
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b36a
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd06a
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b16a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c76a
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b55973446a
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c6a
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.17+1db1cc1f6a
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea2156a
		fabricloader: Fabric Loader 0.16.2
		iris: Iris 1.8.0-beta.2+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.13.0
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
		moremcmeta: MoreMcmeta 1.21-4.4.7
			moremcmeta_animation_plugin: MoreMcmeta Animation Plugin 1.21-1.0.3
			moremcmeta_gui_plugin: MoreMcmeta GUI Plugin 1.21-1.0.1
			moremcmeta_json_parser_plugin: MoreMcmeta JSON Parser Plugin 1.21-1.1.1
			moremcmeta_properties_parser_plugin: MoreMcmeta Properties Parser Plugin 1.21-1.1.5
			moremcmeta_texture_plugin: MoreMcmeta Texture Plugin 1.21-1.0.1
		moremcmeta_emissive_plugin: MoreMcmeta Emissive Textures Plugin 1.21-2.0.5
		nemos-farming: Nemo's Farming 1.1-1.21
			mixinextras: MixinExtras 0.5.0-beta.2
		placeholder-api: Placeholder API 2.4.1+1.21
		sodium: Sodium 0.6.0-beta.1+mc1.21
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 1 / 8; [class_3222['NattoRiisa'/14, l='ServerLevel[New World]', x=-3441.30, y=81.68, z=-1297.09]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, nemos-farming
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, nemos-farming, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -4608486074779006322
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.21

**Comment by NemoNotFound** [comment]
That's weird. I just tested it and it worked perfectly fine

**Comment by NemoNotFound** [comment]
Are you using a mod pack and or did you add them yourself? Could you provide me a mod pack?

**Comment by NattoRiisa** [comment]
> Are you using a mod pack and or did you add them yourself? Could you provide me a mod pack?

all of the instances im using is a hand-crafted modpack by me, i'll send in the second one

the second crash report utilizes:
continuity-3.0.0-beta.5+1.21
emissive-plugin-1.21-2.0.5-fabric
fabric-api-0.102.1+1.21.1
iris-fabric-1.8.0-beta.2+mc1.21.1
lithium-fabric-mc1.21-0.13.0
modmenu-11.0.1
moremcmeta-1.21-4.4.7-fabric
nemos-farming-1.1-1.21
placeholder-api-2.4.1+1.21
sodium-fabric-0.6.0-beta.1+mc1.21

i'll try to reproduce without any other mod but the api AND the mod itself

**Comment by NattoRiisa** [comment]
if its also relevant :
im also using java azul 21

**Comment by NattoRiisa** [comment]
most likely to also happen on savannah villages as well !!! (as it crashes on there)

**Comment by NemoNotFound** [comment]
I think I might have found the issue. I just checked the error message and this: class net.minecraft.class_1542 cannot be cast to class net.minecraft.class_1657  says can't cast ItemEntity to PlayerEntity. Perhaps something like an anvil fell on a farmland. Will fix that immediately and you tell me if it resolved your issue :D

**Comment by NattoRiisa** [comment]
> I think I might have found the issue. I just checked the error message and this: class net.minecraft.class_1542 cannot be cast to class net.minecraft.class_1657 says can't cast ItemEntity to PlayerEntity. Perhaps something like an anvil fell on a farmland. Will fix that immediately and you tell me if it resolved your issue :D

oh !!! alright !!! pass the fix over when its done and i will report back :D

**Comment by NemoNotFound** [comment]
> > I think I might have found the issue. I just checked the error message and this: class net.minecraft.class_1542 cannot be cast to class net.minecraft.class_1657 says can't cast ItemEntity to PlayerEntity. Perhaps something like an anvil fell on a farmland. Will fix that immediately and you tell me if it resolved your issue :D
> 
> oh !!! alright !!! pass the fix over when its done and i will report back :D

Will do, thanks!

**Comment by NattoRiisa** [comment]
> "Perhaps something like an anvil fell on a farmland.
Did exactly that and it crashed!!!
root cause found !!!

**Comment by NemoNotFound** [comment]
Amazing :D
I fixed it and will upload it

**Comment by NattoRiisa** [comment]
> > "Perhaps something like an anvil fell on a farmland.
> Did exactly that and it crashed!!!
> root cause found !!!

more specifically:
~crashes when an anvil falls on a farmland **if** a planted seed is present!~
disregard that !!! still crashes even without a seed!!! tho by chance(?)

**Comment by NattoRiisa** [comment]
got the artifacts (by checking actions)
can report that the crash no longer persists !!! ~will double check if it happens naturally~
doesn't crash manually either !!! happy to report that the crash is now gone !!! thank you!

**Comment by NemoNotFound** [comment]
Nice :D
It's also currently uploading to CurseForge and Modrinth.
Hope you enjoy! Even though I'm far from happy with some textures xD
Need to learn how to do art haha

**Comment by NattoRiisa** [comment]
> Nice :D It's also currently uploading to CurseForge and Modrinth. Hope you enjoy! Even though I'm far from happy with some textures xD Need to learn how to do art haha

its ok !!! i think the overall textures are ok

**Comment by NemoNotFound** [comment]
Thanks!

**Comment by NattoRiisa** [comment]
i will be closing the issue as it has been fixed quickly !!! much appreciated !!!

**Comment by NemoNotFound** [comment]
> i will be closing the issue as it has been fixed quickly !!! much appreciated !!!

No problem! Thanks for reporting it :D
